AllCops:
  TargetRubyVersion: 2.3
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'vendor/**/*'
    - 'bin/**/*'
Style/StringLiterals:
  EnforcedStyle: double_quotes
  SupportedStyles:
    - single_quotes
    - double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes
  SupportedStyles:
    - single_quotes
    - double_quotes
Metrics/LineLength:
    Max: 90
Documentation:
  Enabled: false
Style/DoubleNegation:
  Enabled: false
Style/MultilineBlockChain:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
TrailingCommaInLiteral:
  EnforcedStyleForMultiline: comma
Style/IfUnlessModifier:
  Enabled: false
